# Database
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Redis
spring.data.redis.url=${REDIS_URL}

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=86400000


alphavantage.api-key=${ALPHA_VANTAGE_API_KEY}
alphavantage.base-url=https://www.alphavantage.co/query

# Reddit
reddit.client-id=${REDDIT_CLIENT_ID}
reddit.client-secret=${REDDIT_CLIENT_SECRET}

# Resend
resend.api-key=${RESEND_API_KEY}

# Scheduling
spring.task.scheduling.enabled=true


reddit.user-agent=java:HypeRadar:1.0 (by /u/sbhat72)
reddit.subreddits=wallstreetbets,stocks,investing

rss.feed.reuters=https://feeds.reuters.com/reuters/businessNews
rss.feed.cnbc=https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=10001147
rss.feed.marketwatch=https://feeds.marketwatch.com/marketwatch/topstories/
rss.feed.nasdaq=https://www.nasdaq.com/feed/rssoutbound?category=stocks



